import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const notices = ['react','react-dom','scheduler','react-hot-toast','goober'].map(name => `${name}\n${fs.readFileSync(path.join(dir,'node_modules',name,'LICENSE'),'utf8')}`).join('\n\n');
const output = path.resolve(dir,'../../scripts/toast-runtime.js');
await build({ absWorkingDir:dir,entryPoints:['entry.jsx'],outfile:output,bundle:true,minify:true,format:'iife',platform:'browser',target:['chrome110'],define:{'process.env.NODE_ENV':'"production"'},alias:{goober:path.join(dir,'goober-scoped.js')},legalComments:'eof',
  banner:{js:'/* Generated by tools/toast-runtime/build.mjs; React 18.3.1 / react-hot-toast 2.6.0. */\nwindow.__wbsToastRuntime?.destroy();'},
});
fs.appendFileSync(output,'\n/* Third-party licenses:\n'+notices.replaceAll('*/','* /')+'\n*/\n');
