import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(dir, '../../scripts/markdown-preview.js');
await build({ absWorkingDir: dir, entryPoints: ['entry.js'], outfile: output,
  bundle: true, minify: true, format: 'iife', platform: 'browser', target: ['chrome110'], legalComments: 'eof',
  banner: { js: '/* Generated by tools/markdown-preview/build.mjs; marked 18.0.14 / DOMPurify 3.4.16. */' },
});
const licenses = ['marked', 'dompurify'].map(name => name + '\n' + fs.readFileSync(path.join(dir, 'node_modules', name, 'LICENSE'), 'utf8')).join('\n\n');
fs.appendFileSync(output, '\n/* Third-party licenses:\n' + licenses.replaceAll('*/', '* /') + '\n*/\n');
